"""create knowledge answer versioning

Revision ID: 2826b6baca68
Revises: 
Create Date: 2026-10-10 12:12:44.997326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2826b6baca68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_question', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_answer_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_answer_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("is_current IS False OR status = 'approved'", name='ck_knowledge_answer_versions_current_approved'),
    sa.CheckConstraint("status != 'approved' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)", name='ck_knowledge_answer_versions_approval_metadata'),
    sa.CheckConstraint("status IN ('draft','approved','rejected')", name='ck_knowledge_answer_versions_status'),
    sa.ForeignKeyConstraint(['knowledge_answer_id'], ['knowledge_answers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_answer_id', 'version_number', name='uq_knowledge_answer_versions_item_number')
    )
    op.create_index('uq_knowledge_answer_versions_one_current', 'knowledge_answer_versions', ['knowledge_answer_id'], unique=True, postgresql_where=sa.text('is_current IS true'))
    op.add_column('support_queries', sa.Column('knowledge_version_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'support_queries', 'knowledge_answer_versions', ['knowledge_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'support_queries', type_='foreignkey')
    op.drop_column('support_queries', 'knowledge_version_id')
    op.drop_index('uq_knowledge_answer_versions_one_current', table_name='knowledge_answer_versions', postgresql_where=sa.text('is_current IS true'))
    op.drop_table('knowledge_answer_versions')
    op.drop_table('knowledge_answers')
    # ### end Alembic commands ###
